.TH "_Assertions_Item" 3 "Fri May 12 2023" "LibCE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Assertions_Item \-  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Assertions\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int32_t \fBLine\fP"
.br
.RI "行番号 "
.ti -1c
.RI "char \fBFileName\fP [260]"
.br
.RI "ファイル名 "
.in -1c
.SH "Detailed Description"
.PP 


Assertion item
.PP
Definition at line 58 of file Assertions\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int32_t Line"

.PP
行番号 
.PP
Definition at line 61 of file Assertions\&.h\&.
.SS "char FileName[260]"

.PP
ファイル名 
.PP
Definition at line 63 of file Assertions\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibCE from the source code\&.
