.TH "_Assertions" 3 "Thu May 18 2023" "LibCE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Assertions \-  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Assertions\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBRingedFrames\fP \fBItems\fP"
.br
.RI "Assertion items "
.in -1c
.SH "Detailed Description"
.PP 


Storable assertions
.PP
Definition at line 69 of file Assertions\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBRingedFrames\fP Items"

.PP
Assertion items 
.PP
Definition at line 72 of file Assertions\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibCE from the source code\&.
