.TH "_AvlNode" 3 "Thu May 18 2023" "LibCE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_AvlNode \-  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AvlTree\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int32_t \fBHeight\fP"
.br
.RI "この部分木の高さ "
.ti -1c
.RI "\fBAvlNode\fP * \fBParent\fP"
.br
.RI "親ノード "
.ti -1c
.RI "\fBAvlNode\fP * \fBLeft\fP"
.br
.RI "左部分木 "
.ti -1c
.RI "\fBAvlNode\fP * \fBRight\fP"
.br
.RI "右部分木 "
.ti -1c
.RI "\fBAvlContent\fP \fBContent\fP"
.br
.RI "内容 "
.in -1c
.SH "Detailed Description"
.PP 


AVLノード
.PP
Definition at line 71 of file AvlTree\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int32_t Height"

.PP
この部分木の高さ 
.PP
Definition at line 74 of file AvlTree\&.h\&.
.SS "\fBAvlNode\fP* Parent"

.PP
親ノード 
.PP
Definition at line 76 of file AvlTree\&.h\&.
.SS "\fBAvlNode\fP* Left"

.PP
左部分木 
.PP
Definition at line 78 of file AvlTree\&.h\&.
.SS "\fBAvlNode\fP* Right"

.PP
右部分木 
.PP
Definition at line 80 of file AvlTree\&.h\&.
.SS "\fBAvlContent\fP Content"

.PP
内容 
.PP
Definition at line 82 of file AvlTree\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibCE from the source code\&.
