.TH "_Map" 3 "Thu May 18 2023" "LibCE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Map \-  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Map\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int32_t \fBCount\fP"
.br
.RI "要素数 "
.ti -1c
.RI "\fBAvlNode\fP * \fBRoot\fP"
.br
.RI "木の根 "
.ti -1c
.RI "int32_t \fBCapacity\fP"
.br
.RI "最大要素数 "
.ti -1c
.RI "\fBMapElm\fP * \fBElements\fP"
.br
.RI "要素リスト "
.in -1c
.SH "Detailed Description"
.PP 


Map
.PP
Definition at line 65 of file Map\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int32_t Count"

.PP
要素数 
.PP
Definition at line 68 of file Map\&.h\&.
.SS "\fBAvlNode\fP* Root"

.PP
木の根 
.PP
Definition at line 70 of file Map\&.h\&.
.SS "int32_t Capacity"

.PP
最大要素数 
.PP
Definition at line 72 of file Map\&.h\&.
.SS "\fBMapElm\fP* Elements"

.PP
要素リスト 
.PP
Definition at line 74 of file Map\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibCE from the source code\&.
