.TH "_RingedFrames" 3 "Thu May 18 2023" "LibCE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_RingedFrames \-  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RingedFrames\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int32_t \fBIndex\fP"
.br
.RI "インデックス位置 "
.ti -1c
.RI "int32_t \fBCount\fP"
.br
.RI "フレーム蓄積数 "
.ti -1c
.RI "int64_t \fBUpdateCount\fP"
.br
.RI "フレーム更新数(Pushされた数) "
.ti -1c
.RI "int32_t \fBCapacity\fP"
.br
.RI "最大蓄積可能フレーム数 "
.ti -1c
.RI "int32_t \fBFrameSize\fP"
.br
.RI "最大フレームサイズ "
.ti -1c
.RI "int32_t * \fBBuffer\fP"
.br
.RI "蓄積先バッファ "
.in -1c
.SH "Detailed Description"
.PP 


フレームリングバッファ
.PP
Definition at line 70 of file RingedFrames\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int32_t Index"

.PP
インデックス位置 
.PP
Definition at line 73 of file RingedFrames\&.h\&.
.SS "int32_t Count"

.PP
フレーム蓄積数 
.PP
Definition at line 75 of file RingedFrames\&.h\&.
.SS "int64_t UpdateCount"

.PP
フレーム更新数(Pushされた数) 
.PP
Definition at line 77 of file RingedFrames\&.h\&.
.SS "int32_t Capacity"

.PP
最大蓄積可能フレーム数 
.PP
Definition at line 79 of file RingedFrames\&.h\&.
.SS "int32_t FrameSize"

.PP
最大フレームサイズ 
.PP
Definition at line 81 of file RingedFrames\&.h\&.
.SS "int32_t* Buffer"

.PP
蓄積先バッファ 
.PP
Definition at line 83 of file RingedFrames\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibCE from the source code\&.
