.TH "_SchmittTrigger" 3 "Thu May 18 2023" "LibCE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SchmittTrigger \-  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SchmittTrigger\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBState\fP"
.br
.RI "状態。非0:ON / 0:OFF "
.ti -1c
.RI "int32_t \fBOnCounter\fP"
.br
.RI "ONカウンタ "
.ti -1c
.RI "int32_t \fBOffCounter\fP"
.br
.RI "OFFカウンタ "
.ti -1c
.RI "int32_t \fBOnThreshold\fP"
.br
.RI "ONしきい値 "
.ti -1c
.RI "int32_t \fBOnPeriod\fP"
.br
.RI "ON確定回数 "
.ti -1c
.RI "int32_t \fBOffThreshold\fP"
.br
.RI "OFFしきい値 "
.ti -1c
.RI "int32_t \fBOffPeriod\fP"
.br
.RI "OFF確定回数 "
.in -1c
.SH "Detailed Description"
.PP 


シュミットトリガ
.PP
Definition at line 50 of file SchmittTrigger\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int State"

.PP
状態。非0:ON / 0:OFF 
.PP
Definition at line 53 of file SchmittTrigger\&.h\&.
.SS "int32_t OnCounter"

.PP
ONカウンタ 
.PP
Definition at line 55 of file SchmittTrigger\&.h\&.
.SS "int32_t OffCounter"

.PP
OFFカウンタ 
.PP
Definition at line 57 of file SchmittTrigger\&.h\&.
.SS "int32_t OnThreshold"

.PP
ONしきい値 
.PP
Definition at line 60 of file SchmittTrigger\&.h\&.
.SS "int32_t OnPeriod"

.PP
ON確定回数 
.PP
Definition at line 62 of file SchmittTrigger\&.h\&.
.SS "int32_t OffThreshold"

.PP
OFFしきい値 
.PP
Definition at line 64 of file SchmittTrigger\&.h\&.
.SS "int32_t OffPeriod"

.PP
OFF確定回数 
.PP
Definition at line 66 of file SchmittTrigger\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LibCE from the source code\&.
