.TH "R:/Owned/LibCE/WC/main/inc/ArrayCap.h" 3 "Fri May 12 2023" "LibCE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
R:/Owned/LibCE/WC/main/inc/ArrayCap.h \- Array capacity\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCAPACITY_OF\fP(a)   (sizeof(a) / sizeof((a)[0]))"
.br
.in -1c
.SH "Detailed Description"
.PP 
Array capacity\&. 


.PP
.PP
\fBAuthor\fP
.RS 4
H\&.Someya 
.RE
.PP
\fBDate\fP
.RS 4
2021/08/02
.RE
.PP
MIT License
.PP
Copyright (c) 2021 Hirobumi Someya
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&. 
.PP
Definition in file \fBArrayCap\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define CAPACITY_OF(a)   (sizeof(a) / sizeof((a)[0]))"

.PP
Capacity of array in item count
.PP
\fBParameters\fP
.RS 4
\fIa\fP array
.RE
.PP

.PP
Definition at line 42 of file ArrayCap\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LibCE from the source code\&.
